services:
  db2:
    # IBM Db2 community edition database
    # used with default configuration to test
    # the singer-target
    # "DATABASE=testdb;HOSTNAME=localhost;PORT=50000;PROTOCOL=TCPIP;UID=db2inst1;PWD=pass1"
    image: icr.io/db2_community/db2
    privileged: true
    restart: always
    ports:
    - "50000:50000"
    networks:
      - ci-network
    environment:
    - LICENSE=accept
    - DB2INST1_PASSWORD=pass1
    - DBNAME=testdb
    - DB2COMM=tcpip

  target:
    build:
      context: .
      dockerfile: ci.Dockerfile
    stdin_open: true
    tty: true
    entrypoint: poetry run pytest
    networks:
      - ci-network
    environment:
    - DB2HOST=db2
    depends_on:
      - db2

volumes:
  db2_database:
  db2_home:

networks:
  ci-network:
