name: Release (build & publish to PyPI)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build wheel & sdist"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    ## TODO: optionally provide the name of the environment for the trusted
    ## publisher on PyPI
    ## https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    environment:
      name: release
      url: https://pypi.org/p/target-db2
    permissions:
      id-token: write
      contents: write

    if: startsWith(github.ref, 'refs/tags/')

    steps:

    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: dist/*.whl
        tag: ${{github.ref}}
        overwrite: true
        file_glob: true

    - uses: pypa/gh-action-pypi-publish@v1.9.0
